//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pre_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_Tutor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post_Tutor()
        {
            this.Evaluations = new HashSet<Evaluation>();
        }
    
        public int Post_no { get; set; }
        public string Post_name { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string Tutor { get; set; }
        public string Subject { get; set; }
        public string Price { get; set; }
        public string Sex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual Tutor Tutor1 { get; set; }
    }
}
